// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
     apiKey: "AIzaSyDV_BuUIPw6o5azg3k7_noeoOP1wzBvRXU",
  authDomain: "vedicbhgyaapppp.firebaseapp.com",
  databaseURL: "https://vedicbhgyaapppp-default-rtdb.firebaseio.com",
  projectId: "vedicbhgyaapppp",
  storageBucket: "vedicbhgyaapppp.firebasestorage.app",
  messagingSenderId: "1061531550536",
  appId: "1:1061531550536:web:7f9e14440297582f59a97d",
  measurementId: "G-KEX8F8LQGM",
  );

  static const FirebaseOptions ios = FirebaseOptions(
   apiKey: "AIzaSyDV_BuUIPw6o5azg3k7_noeoOP1wzBvRXU",
  authDomain: "vedicbhgyaapppp.firebaseapp.com",
  databaseURL: "https://vedicbhgyaapppp-default-rtdb.firebaseio.com",
  projectId: "vedicbhgyaapppp",
  storageBucket: "vedicbhgyaapppp.firebasestorage.app",
  messagingSenderId: "1061531550536",
  appId: "1:1061531550536:web:7f9e14440297582f59a97d",
  measurementId: "G-KEX8F8LQGM",
    iosBundleId: 'om.vedicbhagya.partner',
  );
}
